runtime: python312

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)

default_expiration: "6h"

instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 1800ms
  max_pending_latency: 3600ms
  max_concurrent_requests: 1000
